<?php

namespace AppBundle\Repository;

/**
 * CargaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargaisonRepository extends \Doctrine\ORM\EntityRepository
{
}
