<?php

namespace AppBundle\Repository;

/**
 * DetailsMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsMissionRepository extends \Doctrine\ORM\EntityRepository
{
}
