<?php

namespace AppBundle\Repository;

/**
 * RemettantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemettantRepository extends \Doctrine\ORM\EntityRepository
{
}
