<?php

namespace AppBundle\Repository;

/**
 * SuiviMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviMissionRepository extends \Doctrine\ORM\EntityRepository
{
}
