<?php

namespace AppBundle\Repository;

/**
 * TechnicienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicienRepository extends \Doctrine\ORM\EntityRepository
{
}
