<?php

namespace AppBundle\Repository;

/**
 * TracksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TracksRepository extends \Doctrine\ORM\EntityRepository
{
}
