cargaison_index:
    path:     /
    defaults: { _controller: "AppBundle:Cargaison:index" }
    methods:  GET

cargaison_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Cargaison:show" }
    methods:  GET

cargaison_new:
    path:     /new
    defaults: { _controller: "AppBundle:Cargaison:new" }
    methods:  [GET, POST]

cargaison_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Cargaison:edit" }
    methods:  [GET, POST]

cargaison_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Cargaison:delete" }
    methods:  DELETE
