chauffeur_index:
    path:     /
    defaults: { _controller: "AppBundle:Chauffeur:index" }
    methods:  GET

chauffeur_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Chauffeur:show" }
    methods:  GET

chauffeur_new:
    path:     /new
    defaults: { _controller: "AppBundle:Chauffeur:new" }
    methods:  [GET, POST]

chauffeur_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Chauffeur:edit" }
    methods:  [GET, POST]

chauffeur_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Chauffeur:delete" }
    methods:  DELETE
