destinataire_index:
    path:     /
    defaults: { _controller: "AppBundle:Destinataire:index" }
    methods:  GET

destinataire_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Destinataire:show" }
    methods:  GET

destinataire_new:
    path:     /new
    defaults: { _controller: "AppBundle:Destinataire:new" }
    methods:  [GET, POST]

destinataire_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Destinataire:edit" }
    methods:  [GET, POST]

destinataire_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Destinataire:delete" }
    methods:  DELETE
