remettant_index:
    path:     /
    defaults: { _controller: "AppBundle:Remettant:index" }
    methods:  GET

remettant_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Remettant:show" }
    methods:  GET

remettant_new:
    path:     /new
    defaults: { _controller: "AppBundle:Remettant:new" }
    methods:  [GET, POST]

remettant_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Remettant:edit" }
    methods:  [GET, POST]

remettant_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Remettant:delete" }
    methods:  DELETE
