AppBundle\Entity\Remettant:
  exclusion_policy: ALL
  properties:
    id:
      type: integer
      groups: [min_remettant, max_mission, select]
    name:
      groups: [min_remettant, min_mission, max_mission, select]
    address:
      groups: [min_remettant, min_mission, max_mission, select]