AppBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        chauffeur:
          targetEntity: AppBundle\Entity\Chauffeur
          mappedBy: user
        client:
          targetEntity: AppBundle\Entity\Client
          mappedBy: user
    lifecycleCallbacks: {  }
